### ISSUE TITLE
[Bug] Spamming A/D

### ISSUE THREAD

**Issue by Aimsucks** [rbrasga/TLFishingBot#1]
First, I want to say this is absolutely killer and extremely well made. I was able to modify the button regions a bit to make it work for my 1440p game window (not sure what's different from my UI settings to yours, but my Q was like 20 pixels to the right) and test it out. It does a fantastic job with getting the initial hook and snapping, as well as the first stamina bar depletion. After that, it seems to just spam A/D repeatedly until the fish disappears and you fail the hook.

**Comment by Ravalion** [comment]
have you solved the issue? going down to 1/3 of progress bar and then stops

**Comment by VinderOrnitier** [comment]
Many thanks for this work!
Just checked and found the same issue. Maybe 2-3 failed attempts out of 10 because he starts spamming A/D instead of pulling to the opposite side.

**Comment by atitdRhaom** [comment]
How did you fix this?

I am trying to adapt this to work on a 4k monitor, I used the testing.py script which is in PR and matched the boundaries to my screen, took new screenshots and I get no error messages to suggest that the images I am using are not detected and yet literally every single time this script casts, it simply just spams A/D until I am out of stamina, then does not sleep to recover the stamina.

**Comment by locmai0808** [comment]
I'm working on a 1440p version that won't be spamming A/D

**Comment by rbrasga** [comment]
> I'm working on a 1440p version that won't be spamming A/D.
> 
> My current working version for 4k: https://github.com/locmai0808/throne-and-liberty-fishing-bot

I don't think I see this issue. But I'd be happy to accept a pull request.

If it's spamming A/D always, then it's not detecting the fish stamina bar.
